services:
  - type: web
    name: mock-interview
    env: python
    build:
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn --worker-tmp-dir /dev/shm wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mock-interview-db
          property: connectionString
    plan: free
