"""Add content and uploaded_at fields to Resume model

Revision ID: 928f58291a3c
Revises: abe96b02f7b4
Create Date: 2025-05-22 03:06:23.270676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928f58291a3c'
down_revision = 'abe96b02f7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
